version: "3.9"

services:
  api:
    build: .
    image: opentelemetry-template-python:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-devto-news-service}
      - OTEL_SERVICE_VERSION=${OTEL_SERVICE_VERSION:-1.0.0}
      - OTEL_SERVICE_INSTANCE_ID=${OTEL_SERVICE_INSTANCE_ID:-docker-instance}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
