FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

WORKDIR /workspace

COPY requirements.txt /tmp/pip-tmp/
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp

CMD ["sleep", "infinity"]
